lol_tourney/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponse

from webapp import views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^$', views.home, name="index"),
    url(r'^tournaments/$', views.new_tournament_view, name="new_tournament"),
    url(r'^profile/$', views.user_profile_view, name="user_profile"),
    url(r'^remove/(?P<tournament_id>[0-9]+)/', views.remove_from_tournament, name='remove_user'),
    url(r'bootstrap/',views.bootstrap_index, name='bootstrap_index'),
    url(r'tournaments/(?P<tournament_id>[0-9]+)/', views.tournament_detail_view, name="tournament_detail"),
    url(r'riot.txt', lambda r:HttpResponse('50d23f43-950d-4a55-ac72-c14325ec166f', content_type='text/plain')),
]

webapp/models.py
from __future__ import unicode_literals
from datetime import datetime
from django.contrib.auth.models import User
import time
from registration.signals import user_registered

from django.db import models

# Create your models here.
def user_created(sender, user, request, **kwargs):
    user.first_name=request.POST.get('first_name')
    user.last_name=request.POST.get('last_name')
    user.save()

user_registered.connect(user_created)


class UserProfile(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    lol_mmr = models.IntegerField(default=0)
    lol_mmr_last_updated = models.BigIntegerField(default=time.time())
    lol_summoner_name = models.CharField(max_length=255, blank=True, null=True)
    primary_role = models.IntegerField(default=0)
    secondary_role = models.IntegerField(default=0)

    def __str__(self):
        return self.lol_summoner_name or "No User Profile"

    def _get_primary_role(self):
            return {
                0: 'Fill',
                1: 'Top',
                2: 'Jungle',
                3: 'Mid',
                4: 'Bottom',
                5: 'Support',
            }[self.primary_role]

    def _get_secondary_role(self):
            return {
                0: 'Fill',
                1: 'Top',
                2: 'Jungle',
                3: 'Mid',
                4: 'Bottom',
                5: 'Support',
            }[self.secondary_role]

    primary_role_name = property(_get_primary_role)
    secondary_role_name = property(_get_secondary_role)

class Submitted(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    

class Tournament(models.Model):
    teams_created = models.BooleanField(default=False)
    main_user = models.ForeignKey(User,null=True, blank=True, related_name="main_user")
    tournament_name = models.CharField(max_length=255, blank=True, null=True)
    players = models.ManyToManyField('UserProfile',blank=True, related_name="tournament_players")
    deadline = models.DateTimeField(auto_now_add=True, blank=True)
    tournament_key = models.CharField(max_length=255, blank=True, null=True)
    teams = models.ManyToManyField('Team', blank=True, related_name="tournament_teams")
    bracket_json = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.tournament_name

    def _get_number_of_teams(self):
        counter = 0
        for item in self.teams.all():
            counter += 1
        return counter

    number_of_teams = property(_get_number_of_teams)


class Team(models.Model):
    members = models.ManyToManyField('UserProfile')
    team_name = models.CharField(max_length=255, blank=True, null=True)
    ranking = models.IntegerField(default=0)

    def __str__(self):
        return self.team_name

templates/head.html
{%load static%}
<link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
<link href="{%static 'css/style.css'%}" rel="stylesheet">
<link href="{%static 'css/font-awesome.css'%}" rel="stylesheet" />
<script src="{%static 'js/jquery.min.js'%}"></script>
<script src="{%static 'js/bootstrap.min.js'%}"></script>
<script src="{%static 'js/scripts.js'%}"></script>

templates/home.html
<!DOCTYPE html>

<head>
  <title>LolTourney | Home</title>
  {%include 'head.html'%}

</head>
<body>
  <div class="container-fluid">
    {% include 'navbar.html'%}
    <br />
    <br />
    <p>
      Social stuff will be here!<br />
      Maybe blogs and stuff.
    </p>
    <p>
      {% for item in return_survey %}
      {{ item }}<br />
      {% endfor %}
    </p>
  </div>
</body>

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>LOL Tourney</title>
</head>
<body>
<h1>SOME SHIT</h1>
{% if registered == True %}
    <h3> Thank you {{ team_name }}</h3>
{% endif %}
{% if user_profile %}
<h1>Your MMR = {{ user_profile.MMR }}</h1>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="submit">
        SUBMIT
    </button>
</form>
<a href="{% url 'registration_register' %}">Register Here</a>
</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>TITLE</title>
    <link rel="stylesheet" href="{% static 'css/content.css' %}">
  </head>
  <body  style="background-image: url('{% static 'images/background.png' %}')";>
    
    
    <div id="login_menu">
      <p id="login_text">Login</p>
    </div>
    
    
  </body>
</html>

templates/my_profile.html
<!DOCTYPE html>
<head>
  <title>LolTourney|My Profile</title>
  {%include 'head.html'%}

</head>
<body>
  <div class="container-fluid">
    {% include 'navbar.html'%}
    <div class="col-md-6">
      <h1>{{profile.user.first_name}}'s Settings</h1><br />

      <hr />
      {{ user_profile_notification }}
      <form method="post" action=".">
        {% csrf_token %}
        <p>
          <strong>Notes:</strong><br />
          If you choose the same option twice, your probability of being filled increases
          <br />You have a higher chance of getting your primary role if you join the tournaments earlier
          <br /><br />
          <table>
          <label for="id_lol_summoner_name">Lol summoner name:</label>
          <input id="id_lol_summoner_name" maxlength="255" value="{{profile.lol_summoner_name}}" name="lol_summoner_name" type="text">
          <br />
          <label for="id_primary_role">Your first choice:</label>
          <select id="id_primary_role" name="primary_role">
            <option {% if profile.primary_role == 0 %}selected="selected"{% endif %} value="0">Fill</option>
            <option {% if profile.primary_role == 1 %}selected="selected"{% endif %} value="1">Top</option>
            <option {% if profile.primary_role == 2 %}selected="selected"{% endif %} value="2">Jungle</option>
            <option {% if profile.primary_role == 3 %}selected="selected"{% endif %} value="3">Mid</option>
            <option {% if profile.primary_role == 4 %}selected="selected"{% endif %} value="4">Bottom</option>
            <option {% if profile.primary_role == 5 %}selected="selected"{% endif %} value="5">Support</option>
          </select>
          <br />
          <label for="id_secondary_role">Your second choice:</label>
          <select id="id_secondary_role" name="secondary_role">
            <option {% if profile.secondary_role == 0 %}selected="selected"{% endif %} value="0">Fill</option>
            <option {% if profile.secondary_role == 1 %}selected="selected"{% endif %} value="1">Top</option>
            <option {% if profile.secondary_role == 2 %}selected="selected"{% endif %} value="2">Jungle</option>
            <option {% if profile.secondary_role == 3 %}selected="selected"{% endif %} value="3">Mid</option>
            <option {% if profile.secondary_role == 4 %}selected="selected"{% endif %} value="4">Bottom</option>
            <option {% if profile.secondary_role == 5 %}selected="selected"{% endif %} value="5">Support</option>
          </select>
          <p>
            Your current summoner name: {{profile.lol_summoner_name}}<br />
            {% if request.user.is_superuser %}Your MMR: {{profile.lol_mmr}}{%endif%}
          </p>
        </p>
        <input type="submit" value="submit"/>
      </table>
      </form>
    </div>
    <div class="col-md-6">
      <p>
        <h1>My Tournaments:</h1>
        <br />
        <hr />
        <ul>
          {% for tournament in tournaments reversed %}
          <li>
            <a href="{% url 'tournament_detail' tournament_id=tournament.id %}">{{tournament}}</a>
          </li>
          {%endfor%}
        </ul>
      </p>
    </div>
  </div>
</body>

templates/navbar.html
<!--<nav class="navbar navbar-inverse">
<div class="container-fluid">
<div class="navbar-header">
<a class="navbar-brand" href="#">WebSiteName</a>
</div>
<ul class="nav navbar-nav">
<li class="{{active_home}}"><a href="{% url 'index' %}">Home</a></li>
<li class="{{active_tournaments}}"><a href="{% url 'new_tournament' %}">Tournaments</a></li>
<li class="{{active_profile}}"><a href="{% url 'user_profile' %}">Profile</a></li>
<li>
{%if not request.user.is_authenticated%}<a href="{% url 'auth_login' %}">Login</a>&nbsp;{% else %}<a href="{% url 'user_profile' %}">My Profile</a>&nbsp;{%endif%}
</li>
{%if not request.user.is_authenticated%}
<li>
<a href="{% url 'registration_register' %}">Regiter</a>&nbsp;
</li>
{%endif%}
</ul>
<ul class="nav navbar-nav navbar-right">
<li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
<li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
</ul>
</div>
</nav>
-->
<div class="row">
  <div class="col-md-12">
    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
      <div class="navbar-header">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
        </button> <a class="navbar-brand" href="#">LolTourney</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="{{active_home}}"><a href="{% url 'new_tournament' %}">Home</a></li>
          <li class="{{active_tournaments}}"><a href="{% url 'new_tournament' %}">Tournaments</a></li>
          <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
          <ul class="dropdown-menu">
          <li>
          <a href="#">Action</a>
        </li>
        <li>
        <a href="#">Another action</a>
      </li>
      <li>
      <a href="#">Something else here</a>
    </li>
    <li class="divider">
  </li>
  <li>
  <a href="#">Separated link</a>
</li>
<li class="divider">
</li>
<li>
<a href="#">One more separated link</a>
</li>
</ul>
</li>-->
</ul>
<!--<form class="navbar-form navbar-left" role="search">
<div class="form-group">
<input type="text" class="form-control">
</div>
<button type="submit" class="btn btn-default">
Submit
</button>
</form>-->
<ul class="nav navbar-nav navbar-right">
  <li>
    {%if not request.user.is_authenticated%}<a href="{% url 'auth_login' %}"><span class="fa fa-unlock-alt"></span> Login</a>{% else %}<a href="{% url 'user_profile' %}"><span class="fa fa-drivers-license-o"></span> My Profile</a>{%endif%}
  </li>
  <li>{%if not request.user.is_authenticated%}<a href="{%url 'registration_register'%}"><span class="fa fa-user-plus"></span> Sign Up</a>{%else%}<a href="{%url 'auth_logout'%}"><span class="fa fa-sign-out"></span> Logout</a>{%endif%}</li>
  <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
</ul>
</div>

</nav>
</div>
</div>
</div>
<br />
<br />

templates/settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Team Maker</title>
</head>
<body>
    <h1>User Settings</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% if summoner_not_found %}
            <h2>Summoner not found. Please retry</h2>
        {% endif %}
        {{ form.as_p }}
        <button type="submit" value="submit">SUBMIT</button>
    </form>
</body>
</html>

templates/tournament.html
<!DOCTYPE html>
{%load static %}
<head>
  <title>LolTourney | Tournaments</title>
  {%include 'head.html'%}
</head>
<body>
  <div class="container-fluid">
    {% include 'navbar.html'%}
    <div class="col-md-12">
      <h1>Tournament Home</h1>
      <hr />
      <p>
        {{tournament_notification}}<br />
        <strong>Register for tournament here :</strong>
        <br />
        {% if request.user.is_authenticated %}
        <form method="post" action=".">
          {% csrf_token %}
          <h4>Join Tournament</h4>
          <input type="text" name="tournament_id" placeholder="Enter Tournament ID"/>
          <input type="password" name="tournament_key" placeholder="Enter Tournament Key" />
          <input type="submit" name="submit_key" value="submit" />
        </form>
        <form method="post" action=".">
          {% csrf_token %}
          <h4>New Tournament</h4>
          <input id="id_tournament_name" maxlength="255" placeholder="Tournament Name" name="tournament_name" type="text">
          <input id="id_tournament_key" maxlength="255" name="tournament_key" placeholder="Enter Key" type="text">
          <input type="submit" name="submit_tournament" value="submit"/>
        </form>
      </p>
      {%else%}
      <p>
        Please Login to create or join tournaments!
      </p>
      {%endif%}
      <hr />
      <h3>Available tournaments:</h3>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <td>
              Tournament ID
            </td>
            <td>
              Tournament Name
            </td>
            <td>
              Tournament Key
            </td>
            <td>
              Game
            </td>
          </tr>
        </thead>
        <tbody>
          {% for tournament in tournaments reversed %}
          <tr>
            <td>
              <a href={%url 'tournament_detail' tournament_id=tournament.id %}>{{tournament.id}}</a>
            </td>
            <td>
              <a href={%url 'tournament_detail' tournament_id=tournament.id %}>{{tournament.tournament_name}}</a>
            </td>
            <td>
              {{tournament.tournament_key}}
            </td>
            <td>
              League of Legends
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </body>
  </html>

templates/tournament_detail.html
<!DOCTYPE html>
{% load static %}
<head>
  <title>LolTourney | Tournament 1</title>
  {% include 'head.html' %}
  <script type="text/javascript" src="{% static 'js/jquery.bracket.min.js'%}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.bracket.min.css' %}" />
</head>
<body style="margin-left:2vh;">
  <script type="text/javascript">
      var minimalData = {
          teams : [
            ["Team 1", "Team 2"], /* first matchup */
            ["Team 3", "Team 4"],  /* second matchup */
            ["Team 5", "Team 6"],
            ["Team 7", null],
          ],
          results : [
            [[4,3,'Match 1']],       /* first round */
            [[4,6], [2,1]]        /* second round */
          ]
        }

      $(function() {
          $('#minimal .demo').bracket({
            init: minimalData /* data to initialize the bracket with */ })
        })

  </script>
  <div class="container-fluid">
    {% include 'navbar.html'%}
    <div class="row">
    <div class="col-md-12">

      <h1>Tournament: {{ tournament.tournament_name}}</h1>
      <h3>Key: {{tournament.tournament_key}}</h3>
      <hr />
      <div id="minimal" class="col-md-7">
        <div class="demo">

        </div>
      </div>
      <div class="col-md-5">
        Tips for moderators:
        <ol>
          <li>Please refresh page before submitting a new score. This is to avoid one score-set overlapping another.</li>
          <li>Before creating a tournament, make sure the number of possible teams are divisible by 4.</li>
          <li>If the number of teams is in the order of '4n + 1', the last team will have an unfair advantage. Meaning, don't let there be 5,9,13,... teams</li>
          <li>'4n - 1' teams will cause one team to pass to the second round by default. If teams are seeded, this will be the best team.</li>
        </ol>
      </div>
    </div>
    </div>
      {% if not tournament.teams_created %}
      <p>
        Players:
        <ul>
          {% for player in tournament.players.all%}
          <li>
            {{player.lol_summoner_name}} {%if player.user == request.user %}<a href="{% url 'remove_user' tournament_id=tournament.id %}">remove me</a>{%endif%}
          </li>
          {%endfor%}
        </ul>
        <p>
          Teams not set yet. Come back after deadline!
          {% if main_user == True %}
          <form method="post" action=".">
            {%csrf_token%}
            <input type="submit" name="create_teams" />
          </form>
          {% endif %}
        </p>
      {% else %}
        Teams:
        <ul>
          {% for team in tournament.teams.all %}
          <li>
            {{team.team_name}}
          </li>
          {% endfor %}
        </ul>
      </p>
      <p>
        {% if request.user == tournament.main_user %}
        <form method="post" action=".">
          {% csrf_token %}
          <input type="text" placeholder="Match Number" />
          <input type="text" placeholder="Winner" />
          <input type="submit" name="update_bracket" />
        </form>
        {% endif %}
      </p>
      {% endif %}
    </div>
  </div>
</body>